plugins {
	id 'java'
	id 'org.springframework.boot' version "${bootVersion}"
	id 'io.spring.dependency-management' version "${depMgtVersion}"
    id 'io.freefair.lombok' version "${freefairLombokVersion}"
    id 'jacoco'
    id 'com.diffplug.spotless' version "${spotlessVersion}"
    id 'com.google.protobuf' version "${protobufPluginVersion}"
}

group = sysGroup
version = sysVersion

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(javaVersion)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}

    configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-neo4j'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation "com.google.guava:guava:${googleGuavaVersion}"
    implementation "org.apache.commons:commons-lang3:${apacheCommonsLang3Version}"
    implementation "com.sun.xml.bind:jaxb-osgi:${jaxbOsgiVersion}"
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    implementation "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'

    implementation "org.json:json:${orgJsonVersion}"
    implementation "org.springframework.cloud:spring-cloud-starter-openfeign:${openfeignVersion}"

    testRuntimeOnly "org.apache.logging.log4j:log4j-core"
    testRuntimeOnly "org.apache.logging.log4j:log4j-jul"
    testRuntimeOnly "org.apache.logging.log4j:log4j-slf4j-impl"

    // gRPC Dependencies
    implementation "net.devh:grpc-server-spring-boot-starter:${grpcStarterVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "com.google.protobuf:protobuf-java:${protobufVersion}"

    implementation "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
    implementation "javax.annotation:javax.annotation-api:${javaxAnnotationVersion}"

    testImplementation "net.devh:grpc-server-spring-boot-starter:${grpcStarterVersion}"
}

tasks.register('installLocalGitHook', Copy) {
    from file("$rootProject.rootDir/scripts/pre-commit")
    into file("$rootProject.rootDir/.git/hooks")
    filePermissions { permissions ->
        permissions.user.read = true
        permissions.user.write = true
        permissions.group.read = true
        permissions.other.read = true
    }
}

tasks.named('compileJava') {
    dependsOn tasks.named('installLocalGitHook')
}

tasks.named('build') {
    dependsOn 'spotlessApply'
}

tasks.named('test') {
	useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('mockito-core') }}", '-Xshare:off'
}

jacoco {
    toolVersion = jacocoVersion
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect(({
            fileTree(dir: it, exclude: [
                    'com/dongpv/sns/profile/dto/**',
                    'com/dongpv/sns/profile/entity/**',
                    'com/dongpv/sns/profile/mapper/**',
                    'com/dongpv/sns/profile/configuration/**'
            ])
        } as Closure<Object>))))
    }
}

spotless {
    java {
        removeUnusedImports()
        toggleOffOn()
        trimTrailingWhitespace()
        endWithNewline()
        leadingSpacesToTabs()
        palantirJavaFormat()
        importOrder("java", "jakarta", "org", "com", "com.diffplug")
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }
    generateProtoTasks {
        all().each {task ->
            task.plugins {
                grpc {}
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs("build/generated/source/proto/main/grpc")
            srcDirs("build/generated/source/proto/main/java")
        }
    }
}
